site_name: My Docs

theme:
  name: null
  custom_dir: material
  palette:
    scheme: default
  font: false
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - toc.autohide
  icon:
    logo: logo

extra_css:
  - css/colors.css

nav:
  - Tab 1:
      - Page 1.1: 2.md
      - Page 1.2: 1.md
      - Page 1.3: 1.md
  - Tab 2:
    - Page 2.1: 1.md
    - Page 2.2: 1.md
    - Page 2.3: 1.md

markdown_extensions:
  - toc:
      permalink: ⚓︎
      toc_depth: 3 # Define the range of levels to be included in the table of contents
plugins:
  - search
